### ISSUE TITLE
Pinout for Raspberry Pi

### ISSUE THREAD

**Issue by c0dyhi11** [Chouffy/python_sensor_aht20#1]
Hello,

This looks like an awesome Python module to go along with the AHT20. Thanks for your work on this!

It looks like you are using hex values in the AHT20.py to define the pins on the Pi that the sensor is connected to. 

Would it be possible to provide a pinout or picture of which pin is connected where?

That would be very helpful!

Thank you,
Cody Hill

**Comment by Chouffy** [comment]
Hi Cody,

Thanks for your kind message!

I just added my pin output to the Readme: https://github.com/Chouffy/python_sensor_aht20#pinout
Let me know this answer your question!

Kind regards,
Chouffy

**Comment by Chouffy** [comment]
I would add that hex value on top of `AHT20.py` are here to keep hold of commands defined into the datasheet (section 5.4).
I2C output for Raspberry Pi on bus 1 will always be pin #3 for SDA and #5 for SDL.

**Comment by c0dyhi11** [comment]
Awesome! Thanks a bunch!!
